### 
POST http://127.0.0.1:3000/signup
Content-Type: application/json

{
   "name": "Rin Tohsaka",
   "email" : "rin@gmail.com",
   "password" : "12345678",
   "confPassword": "12345678"
}

###
POST http://127.0.0.1:3000/login
Content-Type: application/json

{
   "email" : "mirai@gmail.com",
   "password" : "password"
}

###

GET http://127.0.0.1:3000/cart
Content-Type: application/json